### PR TITLE
Null empty fix

### PR DESCRIPTION
**Pull request by Trovalo**
With reference to issue #28, the values will now be correctly written.
Changes:
- Fields value are now correctly outputted (before it was written even when "ExcludeEmptyMetric" was specified)
- A new function to escape string Field values, for field values only the char (") must be escaped.
- Fixed/edited the existing test to reflect the previous changes
- Added new tests to ensure that empty/null fields are ignored when "ExcludeEmptyMetric" is used

### CODE REVIEW

**Comment by markwragg** [comment]
I don't think your `Out-InfluxEscapeString-Field` function is necessary. `Out-InfluxEscapeString` already handles escaping the `"` character.

**Comment by Trovalo** [comment]
Yes, it escapes that char but the problem is that a different [set of characters](https://docs.influxdata.com/influxdb/v1.7/write_protocols/line_protocol_tutorial/#special-characters-and-keywords) must be escaped.
- For Tag Keys, Tag Values and Field Keys 4 chars must be escaped, ( " " | = | , | " )
- For text Field Values only the double quotes must be escaped ( " ), the value itself must be wrapped with double quotes
- For Measurements, the following chars must be escaped ( " " | , ) ... this is not done yet

As a test:
```
# Insert the following line 
# the not escaped field value is: ciao = "aauhg"
# f2 escapes only the ("), f3 escapes all the special chars
test,a=a f2="ciao = \"aauhg\"",f3="ciao\ \=\ \"aauhg\""

#The Result
SELECT * FROM "xxxx"."yyy"."test"

time	test.f1	test.f2	test.f3
2020-01-08T08:07:22.606Z	1	ciao = "aauhg"	ciao\ \=\ "aauhg"
```

As you can see if all the chars get escaped the "\" will be written in the actual field value.

Also, the backslash char should always be escaped to avoid undesired escapes. (as of now this char is not escaped)

**Comment by markwragg** [comment]
Oh that's interesting. Sorry I wasn't aware of that. In that case then lets add a parameter to the `Out-InfluxEscapeString` function and have it escape differently depending on what Field Type is being escaped. That would be my preference over another function that is largely functionally the same. I'm happy to make that modification but don't have time right now.

**Comment by Trovalo** [comment]
That's a good idea. I will try to implement that when I have some time

**Comment by Trovalo** [comment]
I've edited the function so now you can specify which Influx object (measurement, field value, etc...) you are escaping.
I've also added some more tests to the Escape function, to test all the options.

I did some write tests and so far it's working fine.

**Comment by GWS65** [comment]
Hello Gentlemen,

Thanks a lot!

Gert-Wim

**Pull request merged**
