### PR TITLE
add support for InfluxDB v2.x

### PR DESCRIPTION
**Pull request by R-Studio**
no support for the write over UDP

### CODE REVIEW

**Comment by markwragg** [comment]
Sorry for not coming back to you before now. Thanks for the contribution, i'll try and check it out today.

**Comment by R-Studio** [comment]
no problem, my solution is maybe not perfect but it is working and I hope it helps.

**Comment by markwragg** [comment]
This is great thanks, but I might rework it a little to see if I can ensure there's no breaking change for the current functionality.

**Comment by diveflo** [comment]
Hi:)
No rush, but is this going to be merged at some point? Or ist this repo more or less abandoned?

**Comment by markwragg** [comment]
Its not abandoned, I just haven't had much time to maintain it recently. I will try and look at this soon. I'd still not rather merge this because it is a breaking change, but it shouldn't need too much rework to remove that.

**Comment by markwragg** [comment]
I've completed a refactor of this that I think removes the breaking changes. I've created PR #35 for it as I couldn't add changes to this PR directly. I haven't yet tested the changes however, so need to do that before merging.

The way the refactor works is to just assume if someone provides `-database` and `-credential` then they want to use Influx v1 and if they provide bucket/organisation/token then they want to use Influx v2. This negates the need to add switch parameters.

**Comment by markwragg** [comment]
Superseded by #35

**Pull request closed without merging**
